name: CI - Fullstack Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  # =========================
  # 1. JOB: Teste Backend
  # =========================
  test_backend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run Maven Test
        working-directory: backend/aluno-online
        run: mvn test -Dspring.profiles.active=test

  # =========================
  # 2. JOB: Teste Frontend
  # =========================
  test_frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install & Test
        working-directory: frontend/aluno-online
        run: |
          npm install
          npm test -- --watch=false --browsers=ChromeHeadless

  # =========================
  # 3. JOB: Build Backend
  # =========================
  build_backend:
    name: Build Backend
    needs: test_backend # Só builda se o teste do backend passar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Package JAR
        working-directory: backend/aluno-online
        run: mvn clean package -DskipTests
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: backend/aluno-online/target/*.jar

  # =========================
  # 4. JOB: Build Frontend
  # =========================
  build_frontend:
    name: Build Frontend
    needs: test_frontend # Só builda se o teste do frontend passar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install & Build
        working-directory: frontend/aluno-online
        run: |
          npm install
          npm run build -- --configuration production
      - name: Upload Static Files
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: frontend/aluno-online/dist/aluno-online/